// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const FETCH_USER_PARTY = 'FETCH_USER_PARTY'
export const UPDATE_USER_PARTY = 'UPDATE_USER_PARTY'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR'
export const UPDATE_USER_CV = 'UPDATE_USER_CV'
export const UPDATE_USER_WISHLISTS = 'UPDATE_USER_WISHLISTS'
export const UPDATE_USER_NOTIFICATIONS = 'UPDATE_USER_NOTIFICATIONS'

// navigation.js
export const NAV_TITLE_CHANGE = 'NAV_TITLE_CHANGE'
export const NAV_TOGGLE_OVERLAY = 'NAV_TOGGLE_OVERLAY'

// visit.js
export const FETCH_VISITED_USER = 'FETCH_VISITED_USER'
export const FETCH_VISITED_PROJECT = 'FETCH_VISITED_PROJECT'

// notification.js
export const ATTACH_SNACKBAR = 'ATTACH_SNACKBAR'
export const FETCH_INBOX = 'FETCH_INBOX'
export const UPDATE_INBOX = 'UPDATE_INBOX'
export const FETCH_PROJECTBOX = 'FETCH_PROJECTBOX'
export const UPDATE_PROJECTBOX = 'UPDATE_PROJECTBOX'

// page.js
export const FETCH_SHORTLIST = 'FETCH_SHORTLIST'
