// Regenerates src/lib/icons.ts from the Iconify API.
//
// Run with: node scripts/fetch-icons.mjs
//
// Only the icons listed here are bundled. The legacy app resolved these names against
// api.iconify.design at render time; baking them in removes that request without
// changing which icons the design uses.
import { writeFileSync } from "node:fs";

const WANTED = {
  bx: [
    "bxs-brain", "bx-code", "bx-code-curly", "bxs-data", "bxl-linkedin", "bxs-file-pdf",
    "bx-log-out-circle",
  ],
  entypo: ["paper-plane", "chevron-left", "chevron-small-down", "email", "log-out"],
  "ant-design": [
    "check-circle-outlined", "github-filled", "instagram-outlined",
    "twitter-outlined", "behance-outlined", "field-time-outlined", "star-filled",
  ],
  whh: ["painting", "website", "dribbblealt"],
  ic: [
    "round-check-circle", "round-search", "round-filter-list", "round-link",
    "round-access-time", "round-add-circle", "baseline-work",
    "round-add-circle-outline", "round-remove-circle-outline", "round-block",
    "round-view-headline", "baseline-post-add", "round-supervisor-account",
  ],
  ion: ["arrow-forward-outline", "close", "mail-unread-sharp"],
  carbon: [
    "view-filled", "view-off-filled", "dot-mark", "send-filled", "3rd-party-connected",
  ],
  "fa-solid": ["paint-brush", "dollar-sign"],
  ri: ["team-fill"],
  bi: ["shield-fill-check", "arrow-left-short", "arrow-right-short", "brush"],
  la: ["facebook-f", "certificate-solid", "linkedin-in"],
  "si-glyph": ["paper-plane"],
  dashicons: ["share"],
  mdi: ["whatsapp", "alpha-s-circle-outline", "comma", "dots-horizontal"],
  eva: ["info-outline", "arrow-back-fill", "settings-fill", "globe-2-fill"],
  el: ["flag"],
  maki: ["cross-11"],
  uil: ["enter"],
  zmdi: ["more"],
  "simple-icons": ["polymerproject"],
  clarity: ["success-standard-solid", "times-circle-solid"],
  gridicons: ["stats-up-alt"],
  // The original's share row used Font Awesome's brand marks, not Line Awesome's.
  "fa-brands": ["facebook-f", "line", "pinterest", "telegram-plane", "twitter", "whatsapp"],
};

const collections = {};

for (const [prefix, names] of Object.entries(WANTED)) {
  const url = `https://api.iconify.design/${prefix}.json?icons=${names.join(",")}`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`${prefix}: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  const got = new Set([...Object.keys(data.icons ?? {}), ...Object.keys(data.aliases ?? {})]);
  const missing = names.filter((name) => !got.has(name));

  if (missing.length) {
    throw new Error(`${prefix}: no such icon(s): ${missing.join(", ")}`);
  }

  collections[prefix] = data;
}

const declarations = Object.entries(collections)
  .map(([prefix, data]) => `const ${prefix.replaceAll("-", "_")} = ${JSON.stringify(data)} as const;`)
  .join("\n");

const registrations = Object.keys(collections)
  .map((prefix) => `addCollection(${prefix.replaceAll("-", "_")} as Parameters<typeof addCollection>[0]);`)
  .join("\n");

writeFileSync(
  new URL("../src/lib/icons.ts", import.meta.url),
  `"use client";

// \`addCollection\` is a client-only export of @iconify/react, so this module has to be
// a client module — a Server Component importing it would try to call it across the
// boundary and fail the build. Server Components can still render <Icon>.

import { addCollection } from "@iconify/react";

/**
 * GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
 *
 * The icon sets the original used, bundled rather than fetched. The legacy app loaded
 * Iconify's web component, which resolves every \`data-icon\` against api.iconify.design
 * at render time: a third-party request on every page view, a flash of missing icons
 * while it resolves, and a hard dependency on that API staying up.
 *
 * To add an icon, put its name in WANTED in the script and re-run it.
 */
${declarations}

// Registered at module load; importing this file makes every icon above resolvable
// by its original \`prefix:name\`.
${registrations}

export { Icon } from "@iconify/react";
`,
);

const total = Object.values(collections).reduce((n, d) => n + Object.keys(d.icons ?? {}).length, 0);
console.log(`wrote src/lib/icons.ts — ${total} icons across ${Object.keys(collections).length} sets`);
