// Regenerates src/lib/icons.ts from the Iconify API.
//
// Run with: node scripts/fetch-icons.mjs
//
// Only the icons listed here are bundled. The legacy app resolved these names against
// api.iconify.design at render time; baking them in removes that request without
// changing which icons the design uses.
import { writeFileSync } from "node:fs";

const WANTED = {
  bx: ["bxs-brain", "bx-code", "bx-code-curly", "bxs-data", "bxl-linkedin", "bxs-file-pdf"],
  entypo: ["paper-plane"],
  "ant-design": [
    "check-circle-outlined", "github-filled", "instagram-outlined",
    "twitter-outlined", "behance-outlined", "field-time-outlined",
  ],
  whh: ["painting", "website", "dribbblealt"],
  ic: [
    "round-check-circle", "round-search", "round-filter-list", "round-link",
    "round-access-time", "round-add-circle", "baseline-work",
  ],
  ion: ["arrow-forward-outline"],
  carbon: ["view-filled", "view-off-filled"],
  "fa-solid": ["paint-brush", "dollar-sign"],
  ri: ["team-fill"],
  bi: ["shield-fill-check"],
  la: ["facebook-f", "certificate-solid"],
  "si-glyph": ["paper-plane"],
  dashicons: ["share"],
  mdi: ["whatsapp"],
};

const collections = {};

for (const [prefix, names] of Object.entries(WANTED)) {
  const url = `https://api.iconify.design/${prefix}.json?icons=${names.join(",")}`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`${prefix}: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  const got = new Set([...Object.keys(data.icons ?? {}), ...Object.keys(data.aliases ?? {})]);
  const missing = names.filter((name) => !got.has(name));

  if (missing.length) {
    throw new Error(`${prefix}: no such icon(s): ${missing.join(", ")}`);
  }

  collections[prefix] = data;
}

const declarations = Object.entries(collections)
  .map(([prefix, data]) => `const ${prefix.replaceAll("-", "_")} = ${JSON.stringify(data)} as const;`)
  .join("\n");

const registrations = Object.keys(collections)
  .map((prefix) => `addCollection(${prefix.replaceAll("-", "_")} as Parameters<typeof addCollection>[0]);`)
  .join("\n");

writeFileSync(
  new URL("../src/lib/icons.ts", import.meta.url),
  `"use client";

// \`addCollection\` is a client-only export of @iconify/react, so this module has to be
// a client module — a Server Component importing it would try to call it across the
// boundary and fail the build. Server Components can still render <Icon>.

import { addCollection } from "@iconify/react";

/**
 * GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
 *
 * The icon sets the original used, bundled rather than fetched. The legacy app loaded
 * Iconify's web component, which resolves every \`data-icon\` against api.iconify.design
 * at render time: a third-party request on every page view, a flash of missing icons
 * while it resolves, and a hard dependency on that API staying up.
 *
 * To add an icon, put its name in WANTED in the script and re-run it.
 */
${declarations}

// Registered at module load; importing this file makes every icon above resolvable
// by its original \`prefix:name\`.
${registrations}

export { Icon } from "@iconify/react";
`,
);

const total = Object.values(collections).reduce((n, d) => n + Object.keys(d.icons ?? {}).length, 0);
console.log(`wrote src/lib/icons.ts — ${total} icons across ${Object.keys(collections).length} sets`);
